export let json = {
    "soundfxs": [
        {"name": "elevator waiting 98518", "url":"elevator_2jN6tnc"},
        {"name": "epic meal time crow sound", "url":"epic-mealtime-crow-sound"},
        {"name": "shooting stars", "url":"untitled-1_qPskhfn"},
        {"name": "rick rolled", "url":"epic"},
        {"name": "owen wowson 5", "url":"owenwowson5"},
        {"name": "owen wowson 2", "url":"owenwowson2"},
        {"name": "owen wowson 4", "url":"owenwowson4"},
        {"name": "owen wowson 3", "url":"owenwowson3"},
        {"name": "ding-sound-effect", "url":"ding-sound-effect_2"},
        {"name": "mlg air horn", "url": "mlg-air-horn"},
        {"name": "anime wow", "url": "anime-wow22-55326"},
        {"name": "oh yeah", "url": "oh-yeah"},
        {"name": "bateria tum dum tss", "url": "bateria-tum-dum-tss"},
        {"name": "chewbacca", "url": "chewbacca"},
        {"name": "censor beep 1", "url": "censor-beep-1"},
        {"name": "censor beep 2", "url": "censor-beep-2"},
        {"name": "censor beep 3", "url": "censor-beep-3"},
        {"name": "buzzer", "url": "buzzer-89244"},
        {"name": "minecraft hurt", "url": "minecraft-hurt"},
        {"name": "sad trombone", "url": "sad-trombone"},
        {"name": "whip", "url": "whip"},
        {"name": "u cant touch this", "url": "u-cant-touch-this"},
        {"name": "hitmarkermp3", "url": "hitmarkermp3"},
        {"name": "error sound", "url": "error-soundss-25534"},
        {"name": "door knocking sound effect", "url": "door-knocking-sound-effect-614"},
        {"name": "hello darkness my old frieend", "url": "hello-darkness-my-old-frieend"},
        {"name": "finish him", "url": "finishhim"},
        {"name": "mario jump", "url": "mario-jump"},
        {"name": "clapping", "url": "clapping"},
        {"name": "wrong", "url": "wrong"},
        {"name": "mario 1 up", "url": "mario-1-up"},
        {"name": "snoop dogg meme", "url": "snoop-dogg-meme-88682"},
        {"name": "ka ching", "url": "ka-ching"},
        {"name": "spongebob a few moments later ", "url": "spongebob-a-few-moments-later-"},
        {"name": "doh", "url": "doh"},
        {"name": "bongo feet", "url": "bongo-feet"},
        {"name": "gayyyy", "url": "gayyyy"},
        {"name": "kids cheering", "url": "kids-cheering"},
        {"name": "surprise motherfucka", "url": "surprise-motherfucka"},
        {"name": "aint nobody got time", "url": "aint-nobody-got-time"},
        {"name": "dun dun", "url": "dun-dun"},
        {"name": "i like turtles", "url": "i-like-turtles"},
        {"name": "mario jump", "url": "mario-jump"},
        {"name": "epic sax button", "url": "epic-sax-button"},
        {"name": "cuek", "url": "cuek"},
        {"name": "thug life instrumental", "url": "thug-life-instrumental"},
        {"name": "punch1", "url": "punch1"},
        {"name": "dolphin censor", "url": "dolphin-censor"},
        {"name": "bruh meme", "url": "bruh-meme-44087"},
        {"name": "jeopardy", "url": "jeopardy"},
        {"name": "sonic ring", "url": "sonic-ring"},
        {"name": "wilhelm scream", "url": "wilhelm-scream"},
        {"name": "sneaky snitch", "url": "sneaky-snitch"},
        {"name": "eye of the tiger", "url": "eye-of-the-tiger"},
        {"name": "please stand by", "url": "please-stand-by-87234"},
        {"name": "sitcom audience laughing", "url": "sitcom-audience-laughing-55566"},
        {"name": "ill be bac", "url": "ill-be-bac"}
    ],