export const soundfx = [
    {"name": "elevator waiting", "url":"elevator_2jN6tnc"},
    {"name": "epic meal time crow sound", "url":"epic-mealtime-crow-sound"},
    {"name": "shooting stars", "url":"untitled-1_qPskhfn"},
    {"name": "rick rolled", "url":"epic"},
    {"name": "owen wowson 5", "url":"owenwowson5"},
    {"name": "owen wowson 2", "url":"owenwowson2"},
    {"name": "owen wowson 4", "url":"owenwowson4"},
    {"name": "owen wowson 3", "url":"owenwowson3"},
    {"name": "ding-sound-effect", "url":"ding-sound-effect_2"},
    {"name": "mlg air horn", "url": "mlg-air-horn"},
    {"name": "anime wow", "url": "anime-wow-sound-effect_Q6Q4ech"},
    {"name": "oh yeah", "url": "oh-yeah"},
    {"name": "bateria tum dum tss", "url": "bateria-tum-dum-tss"},
    {"name": "chewbacca", "url": "chewbacca"},
    {"name": "censor beep 1", "url": "censor-beep-1"},
    {"name": "censor beep 2", "url": "censor-beep-2"},
    {"name": "censor beep 3", "url": "censor-beep-3"},
    {"name": "buzzer", "url": "wrong-answer-sound-effect"},
    {"name": "minecraft hurt", "url": "minecraft-hurt"},
    {"name": "sad trombone", "url": "sad-trombone"},
    {"name": "whip", "url": "whip"},
    {"name": "u cant touch this", "url": "mc-hammer-u-cant-touch-this"},
    {"name": "hitmarkermp3", "url": "hitmarker_2"},
    {"name": "error sound", "url": "error_CDOxCYm"},
    {"name": "door knocking sound effect", "url": "crazy-realistic-knocking-sound-troll-twitch-streamers_small"},
    {"name": "hello darkness my old frieend", "url": "saaaadaffleck"},
    {"name": "finish him", "url": "finishhim"},
    {"name": "mario jump", "url": "mario-jump"},
    {"name": "clapping", "url": "clapping"},
    {"name": "wrong", "url": "wrong"},
    {"name": "mario 1 up", "url": "mario-1-up"},
    {"name": "snoop dogg meme", "url": "tmpbxydyrz3"},
    
    {"name": "thug life (snoop)", "url": "snoop-dogg-base-instrumental-mp3cut"},
    {"name": "ka ching", "url": "ka-ching"},
    {"name": "spongebob a few moments later ", "url": "a-few-moments-later-hd"},
    {"name": "doh", "url": "doh"},
    {"name": "bongo feet", "url": "bongo-feet"},
    {"name": "gayyyy", "url": "gayyy"},
    {"name": "kids cheering", "url": "kids_cheering"},
    {"name": "surprise motherfucka", "url": "surprise-motherfucka"},
    {"name": "aint nobody got time", "url": "aint-nobody-got-time"},
    {"name": "dun dun", "url": "dun-dun"},
    {"name": "i like turtles", "url": "i-like-turtles"},
    {"name": "mario jump", "url": "mario-jump"},
    {"name": "epic sax button", "url": "epic-sax-guy-plays-for-57-minutes"},
    {"name": "cuek", "url": "cuek"}, 
    {"name": "punch1", "url": "punch"},
    {"name": "dolphin censor", "url": "spongebob-dolphin-censor"},
    {"name": "bruh meme", "url": "movie_1_C2K5NH0"},
    {"name": "jeopardy", "url": "jeopardy"},
    {"name": "sonic ring", "url": "26f8b9_sonic_ring_sound_effect"},
    {"name": "wilhelm scream", "url": "wilhelmscream"},
    {"name": "sneaky snitch", "url": "sneaky-snitch"},
    {"name": "eye of the tiger", "url": "eye-of-the-tiger"},
    {"name": "please stand by", "url": "please-stand-by-video-effect"},
    {"name": "sitcom audience laughing", "url": "sitcom-laughing"},
    {"name": "ill be back", "url": "ill-be-back"}
];